[Msg]
CT		{Configuration Tools:}
CTList		{       Themes Selector        |       General Settings        |       FVWM Themes Sessions      }
ThemesList	{List of Themes:}
Readme		{ReadMe}
LoadAll		{Load All}
LoadLook	{Load Look}
MSelTheme	{You must select a theme first}
BComponent	{ }
AComponent	{ Components:}
NoThemeSel	{No Theme Selected}
Load		{Load}
Info		{Info}
View		{View}
MSelThemeCp	{You must select a theme component first}
MSelCC		{You must select a used or a set component first}
NoScreenShot	{ScreenShots are not available yet}
NoHelp		{Help is not available yet}
USThemeComp	{Used and Set Theme Components:}
Properties	{Properties}
Restore		{Restore}
Drop		{Drop}
Lock		{Lock}
Unlock		{Unlock}
NoProp		{This used or set component has no options, variants or subcomponents}
PropEditor	{Property editor for}
AActive		{already active}
ThreeEditor	{Number of Property editors is limited to 3}
CompNotSet	{This used component is not re-set}
DropNotImp	{Dropping currently is not available}
NoDrop		{This component cannot be dropped}
SetUSComp	{Settings: Used and Set Components}
SelAComp	{Select a Component}
VariantsFor	{Variants for}
Set		{Set}
MSelVar		{You must select a variant}
CurSession	{Current Session}
UpTime		{Up Time}
SessionsList	{List of FVWM Themes Sessions}
FinishEdit	{You didn't finish to edit the session}
SelSession	{Selected Session:}
MSelSession	{You must select a session}
BEdit		{Edit }
AEdit		{ session}
Edit		{Edit}
Add		{Add}
Remove		{Remove}
# exact for the next 4
SessionH1	{* To load a session, select it and click on Apply                              }
SessionH2	{* To Reload the current session, click on Refresh                              }
SessionH3	{* A click on "Update" will rebuild the current configuration                   }
SessionH4	{* If you Apply, the not applied changes in the others config tools will be lost}
AddSession	{Add a new session}
NRemoveMain	{You cannot remove the main session}
NRemoveCur	{You cannot remove the currently used session!}
BReallyRem	{Really Remove }
AReallyRem	{?}
# exact
SessionName	{Session Name:         }
# exact
ConfigOf	{Configuration of:     }
Ok		{OK}
Cancel		{Cancel}
Yes		{Yes}
No		{No}
NameNotValid	{The name of the session is not valid}
NameAlreadyU	{The name of the session is already used!}
SysErr		{An Unknown "system" error happen, GASP!}
CNewSession	{Click on Apply to load your new session}
MsgInfo		{Warning and infomation messages are displayed here}
NoChanges	{There are no changes in components to be applied}
AThemeConf	{Applying new theme configurations}
ANewSession	{Loading the new session}
RefreshConf	{Refreshing the current configuration}
UpdateConf	{Updating the current configuration}
Apply		{Apply}
Refresh		{Refresh}
Update		{Update}
Help		{Help}
Quit		{Quit}
