[Msg]
CT		{Konfiguracja:}
CTList		{       Wybór schematów        |       Ustawienia ogólne        |       Sesje pracy FVWM Themes     }
ThemesList	{Schematy:}
Readme		{CzytajTo}
LoadAll		{Za³aduj max.}
LoadLook	{Za³aduj min.}
MSelTheme	{Musisz najpierw wybraæ schemat}
BComponent	{ }
AComponent	{ posiada sk³adniki:}
NoThemeSel	{Nie wybrano schematu}
Load		{Za³aduj jdn.}
Info		{Info}
View		{Podgl±d}
MSelThemeCp	{Musisz najpierw wybraæ sk³adnik}
MSelCC		{Musisz wybraæ u¿ywany lub ustawiæ najpierw nowy sk³adnik}
NoScreenShot	{Zrzut ekranu jeszcze nie zaimplementowany}
NoHelp		{Pomoc jeszcze nie opracowana}
USThemeComp	{Sk³adniki schematów:}
Properties	{W³a¶ciwo¶ci}
Restore		{Przywróæ}
Drop		{Odrzuæ}
Lock		{K³ódka}
Unlock		{Odklucz}
NoProp		{Ten sk³adnik nie posiada opcji, wariantów lub innych mo¿liwo¶ci ustawiania}
PropEditor	{Edytor w³a¶ciwo¶ci dla}
AActive		{ju¿ aktywny}
ThreeEditor	{Liczba edytorów w³a¶ciwo¶ci jest ograniczona do 3}
CompNotSet	{Tego sk³adnika aktualnie w u¿yciu nie mo¿na powtórnie ustawiæ}
DropNotImp	{Odrzucanie jeszcze nie zaimplementowane}
NoDrop		{Ten sk³adnik nie mo¿e byæ odrzucony}
SetUSComp	{Ustawienia sk³adników:}
SelAComp	{Wybierz sk³adnik}
VariantsFor	{Warianty dla}
Set		{Ustaw}
MSelVar		{Musisz wybraæ wariant}
CurSession	{Obecna sesja}
UpTime		{Up Time}
SessionsList	{Lista sesji FVWM Themes}
FinishEdit	{Nie zakoñczy³e¶ edycji obecnej sesji}
SelSession	{Sesja wybrana:}
MSelSession	{Musisz wybraæ sesjê}
BEdit		{Edycja sesji  }
AEdit		{ - czy prze³adowaæ konfiguracjê ?}
Edit		{Edycja}
Add		{Dodaj}
Remove		{Usuñ}
# exact for the next 4
SessionH1	{* Aby za³adowaæ sesjê wybierz j± i kliknij "Zastosuj"                          }
SessionH2	{* Aby prze³adowaæ sesjê kliknij "Od¶wie¿"                                      }
SessionH3	{* Aby zachowaæ obecn± konfiguracjê kliknij "Aktualizuj"                        }
SessionH4	{* Nie zachowane zmiany dotycz±ce poprzedniej konfiguracji zostan± utracone     }
AddSession	{Dodaæ now± sesjê ?}
NRemoveMain	{Nie mo¿na usun±æ sesji "main"}
NRemoveCur	{Nie mo¿na usun±æ sesji obecnie u¿ywanej!}
BReallyRem	{Naprawdê usun±æ }
AReallyRem	{?}
# exact
SessionName	{Nazwa sesji:      }
# exact
ConfigOf	{Konfiguracja:   }
Ok		{Tak}
Cancel		{Nie}
Yes		{Tak}
No		{Nie}
NameNotValid	{Nieprawid³owa nazwa sesji}
NameAlreadyU	{Nazwa sesji jest ju¿ w u¿yciu!}
SysErr		{Nieznany b³±d systemowy, GASP!}
CNewSession	{Aby za³adowaæ now± sesjê kliknij "Zastosuj"}
MsgInfo		{Ostrze¿enia i informacje s± wy¶wietlane tutaj}
NoChanges	{Nie ma ¿adnych zmian dotycz±cych konfiguracji sk³adników}
AThemeConf	{Zachowanie nowej konfiguracji schematu}
ANewSession	{£adowanie nowej sesji}
RefreshConf	{Od¶wie¿enie konfiguracji}
UpdateConf	{Aktualizacja konfiguracji}
Apply		{Zastosuj}
Refresh		{Od¶wie¿}
Update		{Aktualizuj}
Help		{Pomoc}
Quit		{Wyjd¼}
