### Menus:
Menu1		{Plik|Wybór|Wyjd¼}
Menu2		{Konfiguracja ...|Ognisko i u³o¿enie okien|Przesuwanie i zmiana rozmiaru|Stronicowanie i parametry myszy|Okna przechodz±ce i animacje|Aluzje i inne parametry|Wybór...}

### Focus
# no more that 44 characteres for the next 8
FocusPolicy	{ Ognisko }
ClickToFocus	{Kliknij okno w celu uaktywnienia}
MouseFocus	{Ognisko pod±¿a za mysz±}
SloppyFocus	{Ognisko pod±¿a za mysz± i zostaje}
FocusOptions	{ Opcje ogniska }
PassClick	{Klikniête ognisko przekazuje klik do okna}
ClickRaise	{Okno klikniête ods³ania siê}
ColorMap	{"Mapy kolorów" pod±¿aj± za ogniskiem}

### Placement
WinPlacement	{ U³o¿enie okien }
SmartRandom	{ U³o¿enie g³adkie je¶li jest wolne miejsce, schodki, je¿eli nie ma}
SmartActive	{ U³o¿enie g³adkie je¶li jest wolne miejsce, aktywne, je¿eli nie ma}
CleverPlace	{ U³o¿enie sprytne }
CleverPlaceP	{ U³o¿enie sprytne metod± procentow± }
DumbActive	{ U³o¿enie aktywne }
DumbRandom	{ U³o¿enie schodkowe }
PlacementOpt	{ Opcje u³o¿enia okien }
GrabFocus	{ Nowe okno uaktywni siê automatycznie }
PPosition	{ We¼ pod uwagê specyfikacje programowe ( aluzja PPosition) }

### Move & Resize
MoveResize 	{ Przesuwanie i zmiana rozmiaru }
# No more than 25 characteres for the next 2
OpaqueResize	{Na Opak              }
OutLineRes	{W Zarysie            }
# be exact for the next 2
Resizing	{Zmieñ rozmiar:       }
OpaqueMove	{Zmiana rozmiaru Na Opak dla okien, które zajmuj± mniej ni¿}
# No more than 20 characteres
ScreenPer	{% powierzchni ekranu}
# be Exact for the next 6
GeoPosition	{Pozycja okienka geometrii:          }
GeoCenter	{Wy¶rodkowana            }
GeoTopLeft	{U góry po lewej        }
HideGeoWin	{Ukryj okienko geometrii dla:        }
HideResize	{Zmiany rozmiaru             }
HideMove	{Przesuniêcia               }
BuggyMove	{ Uaktywnij t± opcjê w przypadku, gdy przesuwane okna zachowuj± siê niestabilnie}
# Snap attraction
SnapAttract	{ Przyci±ganie okien podczas przenoszenia }
# Same size for the next 2
SnapDist	{Odleg³o¶æ:    }
SnapContext	{Kontekst:     }
# check
SnapPopup	{Ikony i okna|Ten sam rodzaj|Okna|Ikony|Ikony, okna i ekran|Ten sam rodzaj i ekran|Okna i ekran|Ikony i ekran}
#  be exact for the next 6 but the 2nd
SnapGrid	{Siatka przyci±gania:      }
ColorOrPix	{ XOR w kolorze lub piksmapa dla linii oraz gestów myszy }
UseAColor	{U¿yj koloru                  }
UseAPixmap	{U¿yj piksmapy (xpm)                 }
OneColor	{Kolor (piksele):         }
OnePixmap	{Piksmapa (xpm):           }
# check next 2
SColorSel	{Paski kolorów}
StartImages	{piksmapa}

### Paging
Paging		{ Stronicowanie }
# exact
HPaging		{Stronicowanie poziome:       }
VPaging		{Stronicowanie pionowe:       }
CirPaging	{Stronicowanie naprzemienne               }
PagingDelay	{Opó¼nienie przy zmianie strony:                   }
EdgeResist	{Opór dla przenoszenia okien pomiêdzy stronami:    }
PanFrame	{Grubo¶æ naro¿ników podczas stronicowania: (uaktywnij)}
# check
PagingList	{Unieruchomione|100%|90%|75%|66%|50%|33%|25%|10%|5%}
Msec		{msek}
Pixels		{piksele}
### Mouse Parameters
MousePara	{ Parametry myszy }
DoubleClick	{Maksymalne opó¼nienie dla podwójnego klikniêcia:      }
MouseDrag	{Minimalna odleg³o¶æ dla przeci±gania mysz±:           }

### Transient
TransientWin	{ Okna przechodz±ce }
TransNDecor	{ Nie ozdabiaj okien przechodz±cych }
TransRaise	{ Odkrywaj wszystkie okna przechodz±ce razem z oknem g³ównym }
TransLower	{ Zas³aniaj wszystkie okna przechodz±ce razem z oknem g³ównym}
TransMore	{ Nie przekazuj akcji odkryj/zas³oñ z okna przechodz±cego do g³ównego}
TransGrab	{ Nowe okno przechodz±ce uaktywnia siê automatycznie }
### Animation speed
AnimTitle	{ Kontrola zwijania okien, menu oraz ruchów animowanych }
# be exact
ShadeStep	{Liczba kroków podczas zwijania:       }
ShadeScroll	{Animacje okien podczas zwijania                                 }
AnimMenu	{Menu i ruchy animowane: }
AnimSpeed	{Prêdko¶æ (msek)      }
AnimSeq		{Lista pozycji:                  }
AnimEx		{Przyk³ady:    }
# max 24
AnimList	{Domy¶lny|Szybki|Natychmiastowy|Wolny|Wolny/Szybki|Szybki/Wolny}

### Hints
# no more that 39 characteres in title from 111 to 116
HintsTitle	{ U¿yj aluzji nastêpuj±cych typów (potwierd¼ wszystkie !) }
# no more that 39 characteres for the next 6
MWMDecor	{Styl MWM}
OLDHints	{Aluzje OLD}
ButShade	{Akcje MWM}
MWMFunctions	{Funkcje MWM}
GNOMEHints	{Aluzje GNOME}
ButModal	{Ignoruj aluzje modu³ów}
### Busy cursor
BusyTitle	{Poka¿ Zajêty Kursor w trakcie wykonywania nastepuj±cych poleceñ }
### Advanced 
AdvTitle	{ Zaawansowane: patrz manual fvwm2 (ustawienia domy¶lne s± OK!) }
# be exact for the next 2
ColorLimit	{Ogranicz liczbê kolorów do:               }
ModTimeOut	{Maksymalny czas opó¼nienia modu³u:       }

### Preferences
PrefFile	{ Schematy i sk³adniki }
BPrefLoaded	{Sk³adnik o nazwie }
MPrefLoaded	{, pochodz±cy ze schematu }
APrefLoaded	{, zosta³ za³adowany}
# be exact for the next 3
PrefLoad	{Za³aduj konfiguracjê z:           }
PrefSave	{Zapis w schemacie:     }
PrefAnother	{Wybierz inny:                  }
Load		{£adowanie}
Ok		{OK}
Preference	{ Wybór }
# be exact for the next 3 
TryIsGlobal	{"Wypróbuj" dotyczy wszystkich biurek i ekranów, nie tylko obecnego }
DefIsGlobal	{"Domy¶lne" dotyczy wszystkich biurek i ekranów, nie tylko obecnego }
SaveIsGlobal	{"Zapisz" dotyczy wszystkich biurek i ekranów, nie tylko obecnego}

### Bindings
#KeyTitle	{Keyboard Bindings}
#MouseTitle	{Mouse Bindings}
#StrokeTitle	{Mouse Stroke Bindings}
#AppBindTitle	{Preferred Applications}

### End
ConfigLoaded	{ Konfiguracja za³adowana }
Save		{Zapisz}
SavedInter	{ Zapis modyfikacji  (wewnetrznie)}
SavedExter	{ Modyfikacje uwzglêdnione (ogólnie)}
Try		{Wypróbuj}
AppliedInter	{ Modyfikacje zapisane wewnêtrznie}
AppliedExter	{ Modyfikacje zapisane ogólnie}
NoEffectHere	{ Nie stosuje siê }
Error		{B³±d:}
Default		{Domy¶lne}
Help		{Pomoc}
Quit		{Wyjd¼}
