#!/bin/sh

set -e

case "$1" in
	purge|remove|upgrade)
		if [ -x update-alternatives ]; then
			update-alternatives --remove \
				x-window-manager /usr/bin/fvwm-themes-start
			update-alternatives --auto x-window-manager
		fi
		if [ -x /usr/bin/update-menus ]; then
			update-menus
		fi
		;;

	failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
