#!/bin/sh

set -e
	if [ -x /usr/sbin/update-alternatives ] ; then update-alternatives --remove x-window-manager /usr/bin/fvwm-themes-start ; fi 
        if [ -x /usr/sbin/update-alternatives ] ; then update-alternatives --auto x-window-manager ; fi
if [ -x /usr/bin/update-menus ]; then update-menus; fi
