[Font]
ChangeFont	{1}
SelFont		{-cronyx-times-bold-r-*-*-12-*-*-*-*-*-koi8-*}
ShadeFont	{-cronyx-times-medium-r-*-*-12-*-*-*-*-*-koi8-*}
FixedFont	{-cronyx-fixed-medium-r-semicondensed--*-*-*-*-*-*-koi8-*}

[Msg]
CT		{Раздел Конфигурации:}
CTList		{       Выбор Тем              |       Общие Установки       |       Сессии FVWM Themes      }
ThemesList	{Список Тем:}
Readme		{Инфо}
LoadAll		{Взять Все}
LoadLook	{Взять Вид}
MSTheme		{Сначала выберите тему}
BComponent	{Компоненты темы }
AComponent	{:}
NoThemeSel	{Не выбрана тема}
Load		{Взять}
Info		{Инфо}
View		{Снимок}
MSelThemeCp	{Сначала выберите компонент темы}
MSelCC		{Сначала выберите использ. или установ. компонент}
NoScreenShot	{Снимки пока не доступны}
# Why Help is not translated ?
NoHelp		{Help пока не доступен}
USThemeComp	{Используемые и установленные компоненты:}
Properties	{Свойства}
Restore		{Возврат}
Drop		{Удалить}
Lock		{Запереть}
UnLock		{Отпереть}
NoProp		{Этот компонент не имеет опций, вариантов или под-компонентов}
PropEditor	{Редактор свойств для}
AActive		{уже активный}
ThreeEditor	{Число редакторов опций ограничено тремя}
CompNotSet	{Этот компонент не пере-установлен}
DropNotImp	{Пока не доступно}
NoDrop		{Этот компонент не может быть удален}
SetUSComp	{Установки: Используемые и установленные компоненты:}
SelAComp	{Выберите Компонент}
VariantsFor	{Варианты для}
Set		{Установить}
MSelVar		{Сначала выберите вариант}
CurSession	{Текущая Сессия}
UpTime		{Время Работы}
SessionsList	{Список Сессий FVWM Themes}
FinishEdit	{Вы не закончили редактировать сессию}
SelSession	{Выбранная сессия:}
MSelSession	{Сначала выберите сессию}
BEdit		{Редактор сессии }
AEdit		{ }
Edit		{Изменить}
Add		{Добавить}
Remove		{Удалить}
SessionH1	{* Для загрузки сессии, выберите её и нажмите на "Применить"                    }
SessionH2	{* Для перезагрузки текущей сессии, нажмите на "Освежить"                       }
SessionH3	{* Нажатие на "Обновить" перестроит текущую конфигурацию                        }
SessionH4	{* При выборе "Применить" потеряются неприменнённые изменения в других разделах }
AddSession	{Добавить новую сессию}
NRemoveMain	{Вы не можете удалить сессию main}
NRemoveCur	{Вы не можете удалить текущую сессию!}
BReallyRem	{Действительно удалить сессию }
AReallyRem	{?}
# exact
SessionName	{Название сессии:      }
# exact Need Translation!
ConfigOf	{Configuration of:     }
Ok		{Согласие}
Cancel		{Отмена}
Yes		{Да}
No		{Нет}
NameNotValid 	{Такое название сессии не может быть использованно}
NameAlreadyU	{Название сессии уже используется!}
SysErr		{Неизвестная "системная" ошибка, Караул!}
CNewSession	{Выберите "Применить" для загрузки вашей новой сессии}
MsgInfo		{Место для информационных и предупреждающих сообщений}
# Need Translation!
NoNewComp	{No components are set}
AThemeConfig	{Применить новую конфигурацию тем}
ANewSession	{Загрузка новой сессии}
RefreshConf	{Перегрузка текущей конфигурации}
UpdateConf	{Обновление текущей конфигурации}
Apply		{Применить}
Refresh		{Освежить}
Update		{Обновить}
Help		{Помощь}
Quit		{Выход}
