[Msg]
CT		{Einstellungs-Menü:}
CTList		{       Themen Selector        |       Allgemeine Einstellungen        |       FVWM Themen Sessions      }
ThemesList	{Liste der Themen:}
Readme		{Info}
LoadAll		{Lade Alles}
LoadLook	{Lade Stiel}
MSelTheme	{Du mußt erst ein Thema anwählen}
BComponent	{ }
AComponent	{ Komponenten:}
NoThemeSel	{Kein Thema gewählt}
Load		{Lade}
Info		{Info}
View		{Betrachte}
MSelThemeCp	{Du mußt erst eine Thema-komponente wählen}
MSelCC		{Du mußt eine genutzte oder gesetzte Komponente wählen}
NoScreenShot	{Schnappschüsse sind noch nicht verfügbar}
NoHelp		{Hilfe ist noch nicht verfügbar}
USThemeComp	{Genutzte und gesetzte Themen-Komponenten:}
Properties	{Optionen}
Restore		{Rückgängig}
Drop		{Entfernen}
Lock		{Sperren}
Unlock		{Entsperren}
NoProp		{Diese genutzten oder gesetzten Komponenten haben keine Optionen, Variationen oder Unterkomponenten}
PropEditor	{Eigenschaften-Editor für}
AActive		{Bereits aktiv}
ThreeEditor	{Zahl der Eigenschaften-Editoren ist limitiert auf 3}
CompNotSet	{Diese genutzte Komponente ist nicht zurückgesetzt}
DropNotImp	{Entfernen derzeit nicht möglich}
NoDrop		{Diese Komponente kann nicht entfernt werden}
SetUSComp	{Einstellungen: genutzte und gesetzte Komponenten}
SelAComp	{Selektiere eine Komponente}
VariantsFor	{Varianten für}
Set		{Setzen}
MSelVar		{Du mußt eine Variante selektieren}
CurSession	{Laufende Session}
UpTime		{Betriebszeit}
SessionsList	{Anzeigen der FVWM Themes Sessions}
FinishEdit	{Du hast das Bearbeiten der Session nicht abgeschlossen}
SelSession	{Selektierte Session:}
MSelSession	{Du mußt eine Session wählen}
BEdit		{Bearbeiten }
AEdit		{ Session}
Edit		{Bearbeiten}
Add		{Hinzufügen}
Remove		{Löschen}
# exact for the next 4
SessionH1	{Zum laden einer Session, selektiere sie und klicke Übernehmen                  }
SessionH2	{Zum Neuladen der laufenden Session, klicek Auffrischen                         }
SessionH3	{Ein klick auf "Aktualisieren" wird die laufende Konfiguration erneuern         }
SessionH4	{Bei Übernehmen gehen nicht gesicherte Änderung anderer Konfigurationen verloren}
AddSession	{Addiere eine neue Session}
NRemoveMain	{Du kannst nicht die Haupt-Session löschen}
NRemoveCur	{Du kannst nicht derzeit genutzte Session löschen!}
BReallyRem	{Wirklich Löschen }
AReallyRem	{?}
# exact
SessionName	{Session Name:         }
# exact
ConfigOf	{Konfiguration von:     }
Ok		{OK}
Cancel		{Abbruch}
Yes		{Ja}
No		{Nein}
NameNotValid	{Der Name der Session ist nicht gültig}
NameAlreadyU	{Der Name der Session ist bereits in Gebrauch!}
SysErr		{Ein Unbekannter "System" Fehler ist aufgetreten, GASP!}
CNewSession	{Klicke auf Übernehmen um die neue Session zu laden}
MsgInfo		{Warnung und Infomationen werden hier angezeigt}
NoChanges	{Da ist keine Änderung in den Komponenten anzuwenden }
AThemeConf	{Übernehme neue Themen-Konfiguration}
ANewSession	{Laden der neuen Session}
RefreshConf	{Auffrischen der laufende Konfiguration}
UpdateConf	{Aktualisieren der laufende Konfiguration}
Apply		{Übernehmen}
Refresh		{Auffrischen}
Update		{Aktualisieren}
Help		{Hilfe}
Quit		{Ende}
