### Menus:
Menu1		{Datei|Einstellungen|Ende}
Menu2		{Konfigurationen ...|Fokus and Platzierung|Verschiebung & Vergrößerung|Arbeitsplatz-Manager & Maus-Parameter|Flüchtige Fenster & Animationen|Tips & erweiterte Parameter|Voreinstellungen...}

### Focus
# no more that 44 characteres for the next 8
FocusPolicy	{ Fokus Vorgehensweise }
ClickToFocus	{Klick in ein Fenster für den Fokus}
MouseFocus	{Der Fokus folgt der Maus}
SloppyFocus	{Der Fokus folgt der Maus aber unsauber}
FocusOptions	{ Optionen für den Fokus }
PassClick	{Fenster erhält nicht Klick für  Fokus}
ClickRaise	{Ein Klick ins Fenster hebt es an}
ColorMap	{Die "Farbpalette" folgt dem Fokus}

### Placement
WinPlacement	{ Fenster Platzierung }
SmartRandom	{ Platzierung selbstständig wenn Platz frei ist,  wenn nicht wird gestuft}
SmartActive	{ Platzierung selbstständig wenn Platz frei ist, aktiv wenn nicht}
CleverPlace	{ Platzierung immer geschickt }
CleverPlaceP	{ Platzierung immer geschickt (Prozent Methode) }
DumbActive	{ Platzierung ist immer aktiv }
DumbRandom	{ Platzierung ist immer gestuft }
PlacementOpt	{ Optionen für die Fenster Platzierung }
GrabFocus	{ Neues Fenster bekommt den Fokus }
PPosition	{ Berücksichtigt die Programm spezifizierte Position (PPosition Hinweis) }

### Move & Resize
MoveResize 	{ Verschiebung und Vergrößerung }
# No more than 25 characteres for the next 2
OpaqueResize	{Undurchsichtig              }
OutLineRes	{Linien            }
# be exact for the next 2
Resizing	{Vergrößerung:        }
OpaqueMove	{Undurchsichtige Bewegung für Fenster kleiner als        }
# No more than 20 characteres
ScreenPer	{% vom Bildschirm}
# be Exact for the next 6
GeoPosition	{Position der Fenstergeometrie:          }
GeoCenter	{Zentriert               }
GeoTopLeft	{oben links        }
HideGeoWin	{Verstecke die Fenstergeometrie für:     }
HideResize	{Vergrößerung               }
HideMove	{Bewegung                 }
BuggyMove	{ Aktiviere diese Option nur wenn dein Fenster blitzt beim umherschieben }
# Snap attraction
SnapAttract	{ Anziehen der Fenster beim Verschieben }
# Same size for the next 2
SnapDist	{Entfernung:  }
SnapContext	{Zusammenhang: }
# check
SnapPopup	{Ikonen & Fenster|Selber Typ|Fenster|Ikonen|Ikonen, Fenster & Bildschirm|Selber Typ & Bildschirm|Fenster & Bildschirm|Ikonen & Bildschirm}
#  be exact for the next 6 but the 2nd
SnapGrid	{Anziehungs Gitter:      }
ColorOrPix	{ Farbe oder Bild XOR für die Linien (und Striche) }
UseAColor	{Nutze Farbe          }
UseAPixmap	{Nutze Bild (xpm)          }
OneColor	{Eine Farbe (pixels):    }
OnePixmap	{Ein Bild (xpm):   }
# check next 2
SColorSel	{Palette}
StartImages	{Bild}

### Paging
Paging		{ Arbeitsplatzmanager }
# exact
HPaging		{Horizontaler Übergang:    }
VPaging		{Vertikal Übergang:        }
CirPaging	{Rundum verschieben    }
PagingDelay	{Verzögerung bevor eine Seite übergeht:         }
EdgeResist	{Widerstand am Bildschirmrand beim Übergang :   }
PanFrame	{Randdicke beim Überganng von Seiten (wenn aktiv): }
# check
PagingList	{Ausgeschalten|100%|90%|75%|66%|50%|33%|25%|10%|5%}
Msec		{msec}
Pixels		{pixels}
### Mouse Parameters
MousePara	{ Maus-Parameter }
DoubleClick	{Maximale verzögerung für Doppelklick:               }
MouseDrag	{Minimale Entfernung für das Maus-Ziehen:            }

### Transient
TransientWin	{ Flüchtige Fenster }
TransNDecor	{ Nicht flüchtige Fenster dekorieren }
TransRaise	{ Hebe alle flüchtigen Fenster zusammen mit dem Erzeugerfenster }
TransLower	{ Senke alle flüchtigen Fenster zusammen mit dem Erzeugerfenster }
TransMore	{ Übertrage nicht die heben/senken-Aktion vom flüchtigen F. auf den Erzeuger }
TransGrab	{ Ein neues flüchtiges Fenster bekommt automatisch den Fokus }
### Animation speed
AnimTitle	{ Animation für Schattierung, Menüs und animierte Bewegungen }
# be exact
ShadeStep	{Zahl der Schattenstufen:          }
ShadeScroll	{ Animiere das innere vom Fenster mit Schatten                   }
AnimMenu	{Menüs und animierte Bewegung:  }
AnimSpeed	{Schnelligkeit (msec): }
AnimSeq		{Liste von Positionen:          }
AnimEx		{Beispiele:    }
# max 24
AnimList	{Vorgaben|Schnell|Sofort|Langsam|Langsam/Schnell|Schnell/Langsam}

### Hints
# no more that 39 characteres in title from 111 to 116
HintsTitle	{ Nutze die Tips von den folgenten Typen (sag ja zu allen!) }
# no more that 39 characteres for the next 6
MWMDecor	{MWM Decor}
OLDHints	{OLD Hints}
ButShade	{MWM action}
MWMFunctions	{MWM Function}
GNOMEHints	{GNOME Hints}
ButModal	{Ignoriere Modalitäten Hinweise}
### Busy cursor
BusyTitle	{Zeige den Besetzt-Cursor während dem Ausführen folgender Kommandos }
### Advanced 
AdvTitle	{ Erweitert: siehe fvwm2 Manual Page (Voreinstellungen sind gut!) }
# be exact for the next 2
ColorLimit	{Limitiere die Anzahl der Farben zu:        }
ModTimeOut	{Maximale Zeit für ein Module zu Antworten:       }

### Preferences
PrefFile	{ Themen und Dateien }
BPrefLoaded	{Initialisiere laufende Komponenten }
MPrefLoaded	{, vom Thema }
APrefLoaded	{, geladen}
# be exact for the next 3
PrefLoad	{Lade die Konfiguration von: }
PrefSave	{Thema zum speichern:     }
PrefAnother	{Wähle ein anderes:       }
Load		{Lade}
Ok		{OK}
Preference	{ Voreinstellungen }
# be exact for the next 3 
TryIsGlobal	{Akzeptiere "Versuchen" für alle Arbeitsflächen, nicht nur für die Laufende }
DefIsGlobal	{Akzeptiere "Vorgaben" für alle Arbeitsflächen,  nicht nur für die Laufende }
SaveIsGlobal	{Akzeptiere "Speichern" für alle Arbeitsflächen, nicht nur für die Laufende }

#Smilers Änderung
MixedVisualWorkaround	{Gemischte sichtbare Umgebung}
SaveUnder		{Speichere unter}



### Bindings
KeyTitle	{Tastatur Bindungen}
MouseTitle	{Maus Bindungen}
StrokeTitle	{Maus Strich Bindungen}
AppBindTitle	{Bevorzugte Programme}

### End
ConfigLoaded	{ Konfigurationen geladen }
Save		{Speichern}
SavedInter	{ Veränderungen gespeichert (Intern)}
SavedExter	{ Veränderungen gespeichert (Global)}
Try		{Versuchen}
AppliedInter	{ Veränderungen intern angewandt}
AppliedExter	{ Veränderungen global angewandt}
NoEffectHere	{ Dies hat keinen Effekt hier }
Error		{Fehler:}
Default		{Vorgaben}
Help		{Hilfe}
Quit		{Ende}
