[Msg]
CT		{Outils de Configurations:}
CTList		{       Sélecteur de Thèmes        |       Configuration Générale        |        Sessions FVWM Themes     }
ThemesList	{Liste des Thèmes}
Readme		{LisezMoi}
LoadAll		{Sélectionner}
LoadLook	{Le look}
MSelTheme	{Vous devez sélectionner un theme !}
BComponent	{Composantes de }
AComponent	{:}
NoThemeSel	{Pas de thème sélectionné}
Load		{Sélectionner}
Info		{Info}
View		{Aperçu}
MSelThemeCp	{Vous devez sélectionner une composante !}
MSelCC		{Vous devez sélectionner une composante !}
NoScreenShot	{Les Aperçus ne sont pas encore implémentés}
NoHelp		{L'aide n'est pas encore implémentés}
USThemeComp	{Composantes des Thèmes Utilisées et Sélectionnées}
Properties	{Propriétés}
Restore		{Rétablir}
Drop		{Enlever}
Lock		{Bloquer}
Unlock		{Débloquer}
NoProp		{Cette composente n'a pas d'options ni de sous composantes}
PropEditor	{L'éditeur de Propriétés pour}
AActive		{est déjà utilisé}
ThreeEditor	{Vous pouvez utilisez seulement 3 éditeurs de Propriétés}
CompNotSet	{Cette composente n'est pas sélectionnée}
DropNotImp	{"Supprimer" sera implémenté un jour!}
NoDrop 		{Vous ne pouvez pas supprimer cette composente}
SetUSComp	{Composentes Utilisées et Selectionnées}
SelAComp	{Sélectionnez une composante}
VariantsFor     {Variantes pour}
Set		{Sélectionner}
MSelVar		{Vous devez sélectionner une Variante !}
CurSession	{Session Courante}
UpTime		{Up Time}
SessionsList	{Liste des Sessions de FVWM Themes}
FinishEdit	{Vous n'avez pas fini d'éditer la session}
SelSession	{Session Sélectionnée:}
MSelSession	{Vous devez sélectionner une session}
BEdit		{Edition de la session }
AEdit		{ }
Edit		{Éditer}
Add		{Ajouter}
Remove		{Supprimer}
# exact for the next 4
SessionH1	{* Pour charger une session, sélectionné la et cliquer sur Appliquer            }
SessionH2	{* Pour recharger la session courante Cliquer sur "Rafréchire"                  }
SessionH3	{* Cliquer sur "Mise à Jour" pour reconstruire la liste des sessions            }
SessionH4	{* Si vous Appliquer, les changements non sauvés des autres outils seront perdus}
AddSession	{Ajoue d'une session}
NRemoveMain	{Vous ne pouvez pas supprimer la session "main"}
NRemoveCur	{Vous ne pouvez pas supprimer la session courante}
BReallyRem	{On supprime vraiment }
AReallyRem	{ ?}
# exact
SessionName	{Nom de la Session:    }
# exact
ConfigOf	{Configuration de:     }
Ok		{OK}
Cancel		{Annuler}
Yes		{Oui}
No		{Non}
NameNotValid	{Le nom pour la session n'est pas correct}
NameAlreadyU	{Le nom pour la session est déjà utilisé!}
SysErr		{Une erreure "system" inconnu a eu lieu, GASP!}
CNewSession	{Cliquer sur "Appliquer" pour charger votre nouvelle session}
MsgInfo		{Les messages d'erreurs et d'informations s'affichent ici}
# Needs a better translation
NoChanges	{Aucune composante n'est sélectionnées}
AThemeConf	{Chargement de la nouvelle configurartion}
ANewSession	{Chargement de la nouvelle session}
RefreshConf	{Rafréchisement de la configuration}
UpdateConf	{Mise à jour de la configuration}
Apply		{Appliquer}
Refresh		{Rafréchire}
Update		{Mise à jour}
Help		{Aide}
Quit		{Quitter}
